include:
  - local: util/cmake-template.yml

stages:
  - build
#  - analyze
#  - test
#  - deploy

build debian-gcc:
  extends: .build_debian
  tags:
    - debian, gcc
  variables:
    CC: gcc
    CXX: g++
    
build debian-clang:
  extends: .build_debian
  tags: 
    - debian, clang
  variables:
    CC: clang
    CXX: clang++

build win-msvc:
  extends: .build_win
  tags:
    - win, msvc
  variables:   
    CC: cl
    CXX: cl
    PREFIX_PATH: ${QT_PATH}/msvc2019_64

build win-mingw:
  extends: .build_win
  tags:
    - win, mingw
  variables:
    CC: x86_64-w64-mingw32-gcc
    CXX: x86_64-w64-mingw32-g++
    PREFIX_PATH: ${QT_PATH}/mingw_64

build macos-clang:
  extends: .build_macos
  tags:
    - macos, clang
  variables:
    CC: clang
    CXX: clang++

build macos-gcc:
  extends: .build_macos
  tags:
    - macos, gcc
  variables:
    CC: gcc-12
    CXX: g++-12

build dreamcast:
  extends: .build_dreamcast

build psvita:
  extends: .build_psvita

build android-sim:
  extends: .build_android-sim

build ios-sim:
  extends: .build_ios-sim

build webasm:
  extends: .build_webasm
